development:
  adapter: mysql
  encoding: utf8
  database: guinea_pig_development
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: guinea_pig_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: guinea_pig_production
  username: root
  password: 
  host: localhost

