host: wincent.com
port: 443
protocol: https
admin_email: win@wincent.com
admin_name: Wincent Colaiuta
google_web_fonts: https://fonts.googleapis.com/css?family=Inconsolata:400,700|Open+Sans:400italic,700italic,400,700|Yanone+Kaffeesatz:400,700
support_email: support@wincent.com
session_key: _wincent_on_rails_session
session_secret: 26c5cd7d236db2b6add7dfd99b667227739fce2e0be44b00e89ee774368c9862fccb3e1ad00c57b872263f9aa714625ee8e273b929ac
attachment_salt: e803cacdca75416d48ff2af539ff6fb743c327db80d27203b9b8067a73d0ced6
memcached_host: localhost:11211
