production:
  adapter: mysql
  encoding: utf8
  database: wincent_on_rails_production
  username: foo
  password: bar
  host: localhost

development:
  adapter: mysql
  encoding: utf8
  database: wincent_on_rails_production
  username: foo
  password: bar
  host: localhost

test: &TEST
  adapter: mysql
  encoding: utf8
  database: wincent_on_rails_test
  username: foo
  password: bar
  host: localhost

cucumber:
  <<: *TEST

migrations:
  adapter: mysql
  encoding: utf8
  database: wincent_on_rails_production
  username: baz
  password: bing
  host: localhost
