#!/usr/bin/env ruby
require 'pathname'

# memcached requires an absolute path for the -P switch
root = (Pathname.new(__FILE__).dirname + '..').realpath
pidfile = root + 'tmp' + 'memcached.pid'

if not pidfile.exist?
  puts "memcached not running: starting"
  system 'memcached', '-d', '-P', pidfile.to_s, '-l', '127.0.0.1'
elsif `ps x`.split("\n").any? { |line| line.match 'memcached -d' }
  puts "memcached running: stopping"
  pid = pidfile.read.chomp
  system 'kill', '-s', 'QUIT', pid

  # as of right now (memcached 1.2.8, Mac OS X 10.6.3) memcached
  # never cleans up its own PID file
  pidfile.delete
else
  puts "memcached not running but stale PID file found: cleaning up"
  pidfile.delete
end
