#!/bin/sh

if [ $(whoami) != "root" ]; then
  echo "error:: this script requires root privileges"
  exit 1
fi

HOSTNAME=$(hostname)
if [ -f "/usr/local/mysql/data/$HOSTNAME.pid" ]; then
  echo "mysql running: stopping"
  mysqladmin shutdown
else
  echo "mysql not running: starting"
  (cd /usr/local/mysql && sudo -u mysql -b mysqld_safe > /dev/null)
fi
