#!/bin/sh

# Selenium RC downloaded from http://seleniumhq.org/download/ and installed
# using:
#
#   unzip selenium-remote-control-1.0.1-dist.zip
#   cd selenium-remote-control-1.0.1/selenium-server-1.0.1
#   sudo cp selenium-server.jar /usr/local/bin/selenium-server-1.0.1.jar
#   cd /usr/local/bin
#   sudo ln -s selenium-server-1.0.1.jar selenium-server.jar

java -jar /usr/local/bin/selenium-server.jar
