#!/bin/sh

usage() {
  echo "usage: $0 [nginx|all]"
  exit 1
}

test $# = 0 && usage
while test $# != 0; do
  case "$1" in
    nginx)
      START_NGINX=1
      ;;
    all)
      START_NGINX=1
      ;;
    *)
      usage
      ;;
  esac
  shift
done

if [ -n "$START_NGINX" ]; then
  script/nginx
fi
