#!/bin/sh

function check_stale_pid_file()
{
  if [ -f "$1" ]; then
    echo "warning: stale pid file still exists at $1 (removing)"
    rm "$1"
  fi
}

/bin/echo -n "nginx: "
if [ $(ps x | grep -v grep | grep -c 'nginx: master process') -eq 0 ]; then
  echo "stopped"
  check_stale_pid_file 'tmp/nginx.pid'
else
  echo "running"
fi

/bin/echo -n "memcached: "
if [ $(ps x | grep -v grep | grep -c 'memcached -d') -eq 0 ]; then
  echo "stopped"
  check_stale_pid_file 'tmp/memcached.pid'
else
  echo "running"
fi
