#!/bin/sh

/bin/echo -n "nginx: "
if [ $(ps x | grep -v grep | grep -c 'nginx: master process') -eq 0 ]; then
  echo "stopped"
else
  echo "running"
fi

/bin/echo -n "memcached: "
if [ $(ps x | grep -v grep | grep -c 'memcached -d') -eq 0 ]; then
  echo "stopped"
else
  echo "running"
fi

/bin/echo -n "mysqld: "
if [ $(ps ax | grep -v grep | grep -c 'mysqld --basedir') -eq 0 ]; then
  echo "stopped"
else
  echo "running"
fi
