class SupportMailer < ActionMailer::Base
  @@counter = 0

  # Returns a new, unique message ID like:
  #   <499ffcc5.c9707.fe59.1ab80.10.47.support@wincent.com>
  # Made because I don't like the look of the IDs generated by TMail:
  #   <499f31fba33c_e18e1093fb616d@wincent.com.tmail>
  def self.new_message_id
    time = Time.now
    @@counter += 1 # not threadsafe but a race here would be harmless anyway
    sprintf '<%x.%x.%x.%x.%x.%x.support@wincent.com>', time.to_i, time.tv_usec, $$,
      Thread.current.object_id, @@counter, rand(65536)
  end

  def receive msg
    raise 'not yet implemented'
  end
end
